version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=Veterinaria
      - POSTGRES_USER=adminvet
      - POSTGRES_PASSWORD=123fgthg
    ports:
      - 5432
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container_docker
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: veterinariaproy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123fgthg
    ports:
      - "5050:80"
    depends_on:
      - db
    links:
      - db:db
  django_app: 
    build: .
    environment:
      - DB_HOST=db
      - DB_NAME=Veterinaria
      - DB_USER=adminvet
      - DB_PASSWORD=123fgthg
    volumes:
      - .:/code
      - static:/code/Proyecto_Vet/static/
    depends_on: 
      - db

  nginx:
    image: nginx:1.20
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/Proyecto_Vet/static/
    depends_on:
      - django_app


volumes:
  .:
  postgres_data:
  static:
  media:
  perfil: