# Generated by Django 4.0.4 on 2022-04-20 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adopt', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Adopcion',
                'verbose_name_plural': 'Adopciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('des', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mascotas/%Y/%m/%d')),
                ('status', models.CharField(choices=[('in_adoption', 'En Adopcion'), ('adopted', 'Adoptado')], default='in_adoption', max_length=11, verbose_name='Estado')),
                ('breed', models.CharField(max_length=150, verbose_name='Raza')),
                ('rescue_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Rescate')),
                ('age', models.CharField(max_length=3, verbose_name='Edad')),
                ('illness', models.CharField(max_length=250, verbose_name='Enfermedades Padecidas')),
                ('food', models.CharField(default='Dog Chow', max_length=250, verbose_name='Alimentación')),
                ('dpi', models.CharField(max_length=13, verbose_name='DPI')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.category')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detdop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=150, verbose_name='Raza')),
                ('cant', models.IntegerField(default=0)),
                ('adoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.adopcion')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.mascotas')),
            ],
            options={
                'verbose_name': 'Detalle de adopcion',
                'verbose_name_plural': 'Detalle de adopciones',
                'ordering': ['id'],
            },
        ),
    ]
