# Generated by Django 4.0.4 on 2022-04-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='cli',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='dire',
            field=models.CharField(default='', max_length=50, verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adopcion',
            name='dpi',
            field=models.CharField(default='', max_length=13, verbose_name='DPI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adopcion',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adopcion',
            name='last_name',
            field=models.CharField(default='', max_length=150, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adopcion',
            name='motive',
            field=models.CharField(default='', max_length=250, verbose_name='Motivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adopcion',
            name='pet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rol.mascotas'),
            preserve_default=False,
        ),
    ]
