# Generated by Django 4.0.4 on 2022-04-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_alter_adopcion_cli_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_updated',
        ),
    ]
