# Generated by Django 4.0.4 on 2022-04-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_remove_category_date_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotas',
            old_name='categoria',
            new_name='cat',
        ),
    ]
