# Generated by Django 4.0.4 on 2022-04-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0004_alter_adopcion_dpi_delete_detdop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='pet',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='pet',
            field=models.ManyToManyField(to='rol.mascotas'),
        ),
    ]
