# Generated by Django 4.0.4 on 2022-04-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0005_remove_adopcion_pet_adopcion_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='pet',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='pet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rol.mascotas'),
            preserve_default=False,
        ),
    ]
