# Generated by Django 4.0.4 on 2022-04-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0007_alter_adopcion_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rol.mascotas', verbose_name='Mascotas'),
        ),
    ]
