# Generated by Django 4.0.4 on 2022-04-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0008_mascotas_stock_alter_adopcion_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotas',
            old_name='status',
            new_name='sta',
        ),
    ]
