# Generated by Django 4.0.4 on 2022-04-21 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rol', '0009_rename_status_mascotas_sta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisMascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.adopcion')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.mascotas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
