# Generated by Django 4.0.4 on 2022-04-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0010_mismascotas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MisMascotas',
        ),
    ]
