# Generated by Django 4.0.4 on 2022-04-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0011_delete_mismascotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('des', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='stock',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='vaccine',
            field=models.ManyToManyField(to='rol.vacunas', verbose_name='Vacunas'),
        ),
    ]
