# Generated by Django 4.0.4 on 2022-04-22 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0012_vacunas_remove_mascotas_stock_mascotas_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='vaccine',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='rol.vacunas', verbose_name='Vacunas'),
            preserve_default=False,
        ),
    ]
