# Generated by Django 4.0.4 on 2022-05-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0013_remove_mascotas_vaccine_mascotas_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='vaccine',
            field=models.ManyToManyField(to='rol.vacunas', verbose_name='Vacunas'),
        ),
    ]
