# Generated by Django 4.0.4 on 2022-04-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=13, unique=True, verbose_name='DPI'),
        ),
    ]
