# Generated by Django 4.0.4 on 2022-04-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_address_user_date_birthday_user_dni_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dni',
        ),
    ]
