# Generated by Django 4.0.4 on 2022-04-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='DPI'),
            preserve_default=False,
        ),
    ]
