# Generated by Django 4.0.4 on 2022-04-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_dni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
